### ISSUE TITLE
Creation of blank databases

### ISSUE THREAD

**Issue by hwalbert** [Ostrich-Emulators/semtool#3]
The files for the Geo Database and the CoW database should successfully load into the tool but when creating a database the progress bar never stops running and a confirmation message saying the creation was successful or not never appears.  When I close the tool and reopen I am able to attach the created database (which is always the same size of 10,240kb) but it is empty and no nodes are available in the generic perspective and the graph metamodel query returns nothing.

**Comment by hwalbert** [comment]
This problem persists in the latest version of the tool. Database is created but it is empty.  I used the CoW dataset and had this issue.

**Comment by ry99** [comment]
It looks like this is an issue with Blazegraph 2.1 on Windows (https://jira.blazegraph.com/browse/BLZG-1942). I've changed the default database creation to use the standard OpenRDF triplestore instead, and added the option to use Blazegraph if you're not on Windows.
