### ISSUE TITLE
Graph Properties

### ISSUE THREAD

**Issue by hwalbert** [Ostrich-Emulators/semtool#5]
Load the CoW Data
Explore instance of year 1816
Traverse to all CCodes

Graph properties will not reliably come up for me.  Got it to come up once but when I changed ccode labels from ccode to name nothing happened...when I closed the graph label area I could never get it back

**Comment by hwalbert** [comment]
Have to drag the graph properties pane to the left to view

**Comment by ry99** [comment]
I've added a little code to remove the ambiguity with the "one touch expandable" bar and the graph properties button.
