### ISSUE TITLE
Duplicate nodes being created

### ISSUE THREAD

**Issue by hwalbert** [Ostrich-Emulators/semtool#6]
Use The CoW database for example:
Create database and go to explore instance of selected node type.
You will see that there are two entries for a CCode: "100" and "100.0"
The tool treats these are different even though they look exactly the same in the loading sheets.
Only certain node properties on the "100" vs the "100.0"...they should be the same thing with all properties on one node.

**Comment by hwalbert** [comment]
Not sure if this has something to do with it but notice that after you load the CoW database v1 and show the metamodel you see the edge labels duplicated.  (CCode>MemberIn?year  &  CCode>ContiguousTo>CCode should only the the predicate associated with that specific relationship.  They are duplicated currently.)

**Comment by ry99** [comment]
I think these are two separate issues. I've created another ticket here: https://github.com/Ostrich-Emulators/semtool/issues/7#issue-177927238
